application:
  host: 127.0.0.0
  port: 8083

mysql:
  username: root
  password: 123456
  host: localhost
  port: 3306
  database: gnet

# 自行配置
spark:
  hostUrl: "xxxxxxxxxxxxxxxxxxxx"
  appid: "xxxxxxxxx"
  apiSecret: "xxxxxxxx"
  apiKey: "xxxxxxxxxxxxxxxxxx"