application:
  host: 127.0.0.0
  port: 8083

mysql:
  username: root
  password: 123456
  host: localhost
  port: 3306
  database: gnet

# 自行配置
spark:
  hostUrl: "xxxxxxxxxxxxxxxxxxxx"
  appid: "xxxxxxxxx"
  apiSecret: "xxxxxxxx"
  apiKey: "xxxxxxxxxxxxxxxxxx"



#spark:
#  hostUrl: "wss://spark-api.xf-yun.com/v2.1/chat"
#  appid: "7536c1f1"
#  apiSecret: "NWQ3ZjBkZjc2NjdhNzVmMWI1MWEwOGYx"
#  apiKey: "16cb81e3c16811ef01cf766bf7835ecd"